# Generated by Django 5.2 on 2025-04-17 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0006_producto_creado_en_descuento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='estado',
        ),
    ]
