# Generated by Django 5.2 on 2025-04-17 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0007_remove_producto_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='estado',
            field=models.BooleanField(default=True),
        ),
    ]
