# Generated by Django 5.2 on 2025-04-17 20:52

import cloudinary.models
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0008_producto_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='marca',
            name='actualizado_en',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='marca',
            name='creado_en',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='marca',
            name='estado',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='marca',
            name='foto_perfil',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
