# Generated by Django 5.2 on 2025-04-18 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0009_marca_actualizado_en_marca_creado_en_marca_estado_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Descuento',
        ),
    ]
