# Generated by Django 5.2 on 2025-04-20 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0006_usuario_fcm_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='bitacora',
            name='detalle',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bitacora',
            name='dispositivo',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='bitacora',
            name='ip_origen',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bitacora',
            name='modulo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='bitacora',
            name='objeto_afectado',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='bitacora',
            name='referencia_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
