# Generated by Django 4.2 on 2025-04-12 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0002_tipopago_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrito',
            name='estado',
            field=models.CharField(choices=[('activo', 'Activo'), ('confirmado', 'Confirmado'), ('abandonado', 'Abandonado')], default='activo', max_length=20),
        ),
        migrations.AddField(
            model_name='carrito',
            name='total_estimado',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
