# Generated by Django 4.2 on 2025-04-16 10:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0003_carrito_estado_carrito_total_estimado'),
    ]

    operations = [
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_factura', models.CharField(max_length=50, unique=True)),
                ('fecha_emision', models.DateTimeField(auto_now_add=True)),
                ('archivo_pdf_url', models.URLField()),
                ('enviado_por_correo', models.BooleanField(default=False)),
                ('venta', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='factura', to='ventas.venta')),
            ],
        ),
    ]
