# Generated by Django 4.2 on 2025-04-17 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0004_factura'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venta',
            name='obra',
        ),
        migrations.DeleteModel(
            name='Obra',
        ),
    ]
