# Generated by Django 5.2 on 2025-04-19 09:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0010_delete_descuento'),
        ('ventas', '0007_campañadescuento_descuento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='descuento',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='descuentos', to='productos.producto'),
        ),
    ]
